/* The deck is authored as three files - index.html plus the two generated
   stylesheets that carry the font, the portrait and the marks as base64.
   That is fine to edit and wrong to hand to someone: downloading one file
   out of three from GitHub gets you a deck with no typeface and no pictures.

   So this folds the three into presentations/intro/deck.html, which is one
   file that opens anywhere, offline, with nothing beside it. Run it after
   any change to the deck:  node tools/build-deck.mjs                      */
import { readFile, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const dir = join(root, "presentations", "intro");

const html = await readFile(join(dir, "index.html"), "utf8");
const fonts = await readFile(join(dir, "fonts.css"), "utf8");
const media = await readFile(join(dir, "media.css"), "utf8");

/* the two <link>s become one <style>, in the same place, so the cascade
   order the deck was written against is preserved exactly */
const links = '<link rel="stylesheet" href="fonts.css">\n<link rel="stylesheet" href="media.css">';
if (!html.includes(links)) {
  throw new Error("the stylesheet links are not where this script expects them");
}

const one = html
  .replace(links, "<style>\n" + fonts + "\n" + media + "\n</style>")
  .replace("<title>", "<!-- one self-contained file: font, portrait and marks are all inside.\n     Generated by tools/build-deck.mjs - edit index.html, not this. -->\n<title>");

await writeFile(join(dir, "deck.html"), one);
console.log("build-deck -> presentations/intro/deck.html  (" + Math.round(one.length / 1024) + " KB, one file)");
